### ISSUE TITLE
[Feat] Coverage of other scan sites

### ISSUE THREAD

**Issue by brianleect** [brianleect/etherscan-labels#11]
Logic used here should be able to be replicated for other scan sites due to similar structure. Would be good for coverage.

Need further research to determine if site structure / logic used can be re-used.

**Comment by brianleect** [comment]
With the recent changes to etherscan method of displaying labels, it appears that logic may not be entirely reusable.

**Comment by naddison36** [comment]
This would be a fantastic enhancement.

**Comment by brianleect** [comment]
Proposed structure
1. Add folder for each scan prioritizing largest scan sites such as BSC and POLY first likely.
2. Rework flow to ask for site to scrape or simply loop through all (E.g. etherscan, bscscan, polyscan...)

Further actions
1. Rename to evm-labels for clearer representation of project scope

**Comment by brianleect** [comment]
Update, seems that bscscan follows old etherscan format, might be able to just utilize old code.

**Comment by brianleect** [comment]
@naddison36 Latest repo shd have bscscan and polygonscan now. Feel free to bring up any other evm chains of interest you think we should as well.

**Comment by naddison36** [comment]
Thanks @brianleect. Excellent work

**Comment by naddison36** [comment]
@brianleect can you add Optimisim? That's a pretty popular chain
https://optimistic.etherscan.io/

Thanks

**Comment by brianleect** [comment]
@naddison36 currently Optimism scraping is blocked by cloudflare protection

Issue: https://github.com/brianleect/etherscan-labels/issues/18
