### ISSUE TITLE
Need specific Python version with compatible selenium and pandas

### ISSUE THREAD

**Issue by ewagmig** [brianleect/etherscan-labels#13]
When I start this project with python 3.11, there is a lot of compatibility issues on selenuim and pandas. 
So could you specify the exact python version for this project, thanks.

**Comment by brianleect** [comment]
Hi matt, thanks for bringing up the issue.

Seems that in the recent months, Selenium had a major rework breaking one of the functionality which we use, fixing it now. 

https://stackoverflow.com/questions/72773206/selenium-python-attributeerror-webdriver-object-has-no-attribute-find-el

**Comment by ewagmig** [comment]
Thanks @brianleect, yes I found that there is some update w/o backwards compatibility with Selenuim. 
By the way, is there an version with python main script updated according to the etherscan label cloud webpage?

**Comment by brianleect** [comment]
No update is required for label cloud webpage. I just tested the scraper and it still works fine for gathering labels for labelcloud. But we require fixing labels scraping as the way address is displayed just changed.

**Comment by brianleect** [comment]
@ewagmig latest version at main should have fixed it. I made some modifications to remove the need for manual webdriver installation as well

**Comment by ewagmig** [comment]
Thanks @brianleect, but all the labels in webpage is not collected all. e.g.  https://etherscan.io/accounts/label/0x-protocol?subcatid=undefined, only the addresses in table id "main" are scraped, the addresses in other 2 table id  have not been scraped at all. That is only 26/59 of all addresses in this situation. Some updating on the base url should be taken to this scenario.

**Comment by ewagmig** [comment]
Yes, I seems that the data provider, i.e. etherscan.io has just updated its display strategy recently. I think the link https://etherscan.io/accounts/label/0x-protocol?subcatid=3-0 with different `subcatid` input for the tables.

**Comment by brianleect** [comment]
@ewagmig Latest push should have fixed it. Uploaded latest labels as well.

**Comment by brianleect** [comment]
Closing as it should be resolved
