### ISSUE TITLE
[Feat] [Bug] Etherscan Cloudflare bypass

### ISSUE THREAD

**Issue by brianleect** [brianleect/etherscan-labels#18]
Seems that etherscan might have implemented an additional layer of scraping protection. In an attempt to scrape today it appears that while logged in I got blocked by a cloudflare linked page. Might be a major problem.

Will need to research further and see if it occurs often or was a one off case.

**Comment by buggyprogrammer** [comment]
why don't you use undetected-chromedriver, or selenium-wire? They are very good at bypassing anti-bot tests.

**Comment by buggyprogrammer** [comment]
I see you are using simple selenium, which can be caught easily as a bot. Have you tried using [undetected-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver), or [selenium-wire](https://github.com/wkeeling/selenium-wire)? They are very good at bypassing anti-bot tests.

**Comment by brianleect** [comment]
Thanks for the suggestion, I'll take a look at it! Do feel free to open a PR with this integrated if you happen to be more familiar.

Currently it seems that simple selenium works for bscscan and polygonscan but not etherscan.

**Comment by brianleect** [comment]
Might have scraped too heavily, getting the issue on bscscan now as well.

**Comment by brianleect** [comment]
Currently main problem consistently occurs for scraping eth (old scraped done) and optimism (TBD)

**Comment by buggyprogrammer** [comment]
I happened to be working on web scraping a lot these days, I will try implementing selenium-wire or undetected-chromedriver. Hopefully, that will resolve the issue. Can you assign this issue to me?
